import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Amplify from "aws-amplify";
import awsconfig from "../src/aws-exports";

import { DataStore } from '@aws-amplify/datastore';
import { Blog } from '../src/models';

Amplify.configure(awsconfig);

export default function Home() {
  const handleCreateClick = async () => {
    await DataStore.save(
      new Blog({
        name: "Lorem ipsum dolor sit amet 1",
      })
    );

    console.log("Item Ceated")
  };

  const handleUpdateClick = async () => {
    /* Models in DataStore are immutable. To update a record you must use the copyOf function
    to apply updates to the item’s fields rather than mutating the instance directly */
    await DataStore.save(
      Blog.copyOf(CURRENT_ITEM, (item) => {
        // Update the values on {item} variable to update DataStore entry
      })
    );
  };

  const handleDeleteClick = async () => {
    const modelToDelete = await DataStore.query(Blog, "cfb8e0bf-719f-45fb-a0aa-5eeeccc64fda");
    DataStore.delete(modelToDelete);
  };

  const handleViewClick = async () => {
    const models = await DataStore.query(Blog);
    console.log(models);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          <li>
            <button onClick={() => handleCreateClick()}>Create</button>
          </li>
          <li>
            <button onClick={() => handleUpdateClick()}>update</button>
          </li>
          <li>
            <button onClick={() => handleDeleteClick()}>Delete</button>
          </li>
          <li>
            <button onClick={() => handleViewClick()}>View</button>
          </li>
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
